import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'pathe'

export interface WriteTypesOptions {
  rootDir: string
  buildDir?: string
}

export function writeTypes(options: WriteTypesOptions): void {
  const buildDir = options.buildDir ?? resolve(options.rootDir, '.mangia')
  mkdirSync(buildDir, { recursive: true })

  const typeContent = `// Generated by mangia
import type { MangiaPage } from '@mangia/schema'

declare module 'virtual:mangia/pages.ts' {
  import type { Routes } from '@angular/router'
  export const routes: Routes
}

declare module '#app' {
  export interface PageMeta {
    [key: string]: unknown
  }
}

export {}
`

  writeFileSync(resolve(buildDir, 'types.d.ts'), typeContent)
}
