export function generateAppDeclarations(): string {
  return `// Generated by mangia
import type { MangiaPage } from '@mangia/schema'

declare module 'virtual:mangia/pages.ts' {
  import type { Routes } from '@angular/router'
  export const routes: Routes
}

declare module 'virtual:mangia/app-config' {
  import type { ApplicationConfig } from '@angular/core'
  export const appConfig: ApplicationConfig
  export const head: Record<string, unknown>
}

declare module 'virtual:mangia/root-component' {
  import type { Type } from '@angular/core'
  export const __rootComponent: Type<unknown>
}

declare module '#app' {
  export interface PageMeta {
    [key: string]: unknown
  }
}

export {}
`
}

export function generateNodeDeclarations(): string {
  return `// Generated by mangia
import type { MangiaConfig, MangiaModule } from '@mangia/schema'

declare module 'mangia/config' {
  export function defineMangiaConfig(config: MangiaConfig): MangiaConfig
}

declare module 'virtual:mangia/*' {
  const content: unknown
  export default content
}

export {}
`
}

export function generateServerDeclarations(): string {
  return `// Generated by mangia
import type { MangiaConfig } from '@mangia/schema'

declare module 'nitro/vite' {
  import type { Plugin } from 'vite'
  export function nitro(config?: Record<string, unknown>): Plugin[]
}

declare module 'h3' {
  import type { EventHandler } from 'h3'
  export function defineEventHandler(handler: EventHandler): EventHandler
  export function getQuery(event: { query: unknown }): Record<string, string>
  export function readBody<T = unknown>(event: unknown): Promise<T>
}

export {}
`
}

export function generateSharedDeclarations(): string {
  return `// Generated by mangia
export {}
`
}
